### ISSUE TITLE
What's missing?

### ISSUE THREAD

**Issue by henrydobson** [puppetlabs/puppet-in-docker#11]
I have been testing with this container and recently made a new container adding a few additional tools. Python, pip and a module.

This has however resulted in breaking the connection to puppetdb. No doubt I've missed something crucial but I could use a second pair of eyes to help me fix it. Can you help me identify what's going wrong? I originally thought it was my apt-get update, which was updating puppetserver however this doesn't seem to be the case as I put all the puppet packages on hold during my latest docker push. 

**Here's the Dockerfile:** 
https://github.com/henrydobson/docker-puppetserver/blob/master/Dockerfile

**Here's the compose file that works:** 
https://github.com/henrydobson/puppet-in-docker-examples/blob/master/compose/docker-compose.yml

**Here's the compose file that does not work:**
https://gist.github.com/henrydobson/d059010ba04ad2e2363bc4585d44c088

**Here's the error I believe to be most informative about the issue:**
https://gist.github.com/henrydobson/e43f78321cf1b2a58bf98353e6762ea5

**Comment by garethr** [comment]
Hi @henrydobson. Mmm, I'm not spotting anything obvious unfortunately. I'm currently travelling but will try and recreate the issue you're experiencing.

**Comment by henrydobson** [comment]
I haven't had the time to investigate much further on the cause but knocking my FROM container back a few versions fixed the issue.

https://github.com/henrydobson/docker-duo_puppetserver/blob/master/Dockerfile#L1

**Comment by stahnma** [comment]
Closing this since we've had no updates since 2016. (if issues still persist, reopen)
