### ISSUE TITLE
Specified bootstrap file does not exist.

### ISSUE THREAD

**Issue by mhamrick** [puppetlabs/puppet-in-docker#12]
When running the puppetserver, the startup fails with the following issue:

`Exception in thread "main" java.lang.IllegalArgumentException: Specified bootstrap config file does not exist: '/etc/puppetlabs/puppetserver/bootstrap.cfg'`

Full output is below:

https://gist.github.com/mhamrick/ca2aefa8c6b79abcb3ec5c7c382b3641

Below appears to contain a fix, but I am not proficient enough with Docker yet to implement:

https://tickets.puppetlabs.com/browse/SERVER-1247

I first discovered this using the puppet-in-docker compose examples.

**Comment by garethr** [comment]
@mhamrick apologies, I managed to publish broken images yesterday. I'd previously fixed this issue in https://github.com/puppetlabs/puppet-in-docker/commit/d8b67fbc20769ba0b87352f2c78204aee9c7d5d4#diff-3b2e376651b906f8806481faf1eae4b6L16. The images should now work correctly. Thanks for opening and sorry again.
