### ISSUE TITLE
More persistent volumes?

### ISSUE THREAD

**Issue by ms1111** [puppetlabs/puppet-in-docker#13]
Hi @garethr,

Thanks, really cool set of images. I've added the following volumes to my docker-compose.yml and I think they might make sense at the Dockerfile level to ensure persistence of Puppet CA data files and so on.

puppet:
- /etc/puppetlabs/puppet/ssl
- /opt/puppetlabs/server/data/puppetserv
  er/

puppetdb:
- /etc/puppetlabs/puppet/ssl

I'm also supplying /var/lib/postgresql/data as a volume for puppetdb-postgres, but this is already defined as a volume in the upstream postgres image.

I'd be curious to know if you can think of any other state directories that should be saved for a real live Puppet/PuppetDB environment.

And I'm a bit fuzzy on what it means to declare a volume in the Dockerfile. For my purposes it's more important to define volumes in the docker-compose.yml so they get persisted properly. Having them defined in a Dockerfile is more documentation than anything.

Thanks,
Mike

**Comment by garethr** [comment]
I think these are good suggestions. Would you be open to sending a pull request for your changes? 

Exporting volumes in Dockerfiles does act as documentation. Those directories also get automatically mounted as volumes by the run command, even if you don't explicitly mount from the host. This also allows you to do thinks like use the handy `--volumes-from` command at runtime, to package data up in containers and mount it at runtime in another container.

**Comment by ms1111** [comment]
Sure, I've linked a pair of pull requests, one for puppet-in-docker and the other for puppet-in-docker-examples to update the docker-compose.yml.

**Comment by MWilsonPuppet** [comment]
Closing as issue resolved with @ms1111 PR'S merged. Thanks @ms1111.
