### ISSUE TITLE
MCollective

### ISSUE THREAD

**Issue by ms1111** [puppetlabs/puppet-in-docker#14]
It would be nice to have a Dockerfile for MCollective and, since you have a very complete set of images otherwise, I wonder if there's something fundamentally wrong about running MC in Docker?

**Comment by garethr** [comment]
@ms1111 not at all. It would indeed be useful. I haven't managed to get to it yet I'm afraid but I'd like to do so at some point, or if you end up trying to do it yourself please do let me know. I'll leave this open as a good reminder and for anyone else who may be interested.

**Comment by underscorgan** [comment]
We're migrating from github issues to issues on the Puppet JIRA (tickets.puppet.com). I've added this issue as https://tickets.puppetlabs.com/browse/CPR-573
