### ISSUE TITLE
X-Forwarded-For

### ISSUE THREAD

**Issue by vladgh** [puppetlabs/puppet-in-docker#17]
Is there a way for the Puppet Server to use the `X-Forwarded-For` header so that the real ip is logged correctly?

Currently the logs look like this (with the internal ip `172.20.0.3` as the origin for that request)
```
Nov 07 11:07:16 puppet vpm_server_1:  172.20.0.3 - - - 07/Nov/2016:17:07:16 +0000 "POST /puppet/v3/catalog/XXXXXXXXXXX?environment=production HTTP/1.1" 200 104638 172.20.0.3 172.20.0.3 8140 3724
```

**Comment by stahnma** [comment]
How do you do this without a container normally? It could be that some additional configuration options need exposure via ENV vars.

**Comment by trevor-viljoen** [comment]
I have something like this in my config for an nginx reverse-proxy I run in a docker container:
```
proxy_set_header X-Real-IP       $remote_addr;
```

**Comment by underscorgan** [comment]
We're migrating from GitHub issues to tickets in the Puppet JIRA (tickets.puppet.com). I've opened this there at https://tickets.puppetlabs.com/browse/CPR-577
