### ISSUE TITLE
Please can you build a Centos puppet server version 4 on docker?

### ISSUE THREAD

**Issue by qafro1** [puppetlabs/puppet-in-docker#19]
I will like a docker in puppet for Centos 7 or latest puppet server with the latest puppet version?

**Comment by garethr** [comment]
@qafro1 sorry for the long delay in responding here. This is certainly possible, albeit at a slight overhead. Could I ask what the specific user need is here? I'd be interested in understanding as it can then have a knock-on effect for other images too.

**Comment by sdscgithub** [comment]
@garethr we also would like to use server v4 since our infrastructure is built on this version already. Thanks!

**Comment by stahnma** [comment]
We don't have plans to build older version inside containers. My recommendation would be to look at the dockerfiles provides and swap in the version/packages that work for your installation. We're looking at making containers for modern releases however.
