### ISSUE TITLE
Permission errors when mounting ssldir on the host

### ISSUE THREAD

**Issue by vladgh** [puppetlabs/puppet-in-docker#2]
Given the following command: 
```
docker run --rm -it --name puppet -p 8140:8140 -v $(pwd)/certs:/etc/puppetlabs/puppet/ssl puppet/puppetserver
```

Puppetserver tries to set the permissions and fails with multiple errors similar to:
```
2016-06-02 19:01:40,860 INFO  [puppetserver] Puppet Puppet settings initialized; run mode: master
2016-06-02 19:01:47,712 ERROR [puppetserver] Puppet failed to set mode 0755 on /etc/puppetlabs/puppet/ssl: Operation not permitted - No message available
org/jruby/RubyFile.java:614:in `chmod'
```

Solution would be to change the ownership of ssldir in an entrypoint, before puppetserver starts:
```
SSLDIR="$(puppet config print ssldir)"
mkdir -p "$SSLDIR"
chown -R puppet:puppet "$SSLDIR"
```

If it's more convenient I can open a PR. I have the code already in my own puppetserver images.

**Comment by garethr** [comment]
Hi @vladgh. Thanks for the heads up. I've gone ahead and fixed in https://github.com/puppetlabs/puppet-in-docker/commit/093132b2d0bc766a55c7820fab69d7bcd945aeb6.
