### ISSUE TITLE
Issue certificate : Puppet Server standalone 

### ISSUE THREAD

**Issue by qafro1** [puppetlabs/puppet-in-docker#20]
Error: Could not request certificate: Failed to open TCP connection to puppet:8140 (getaddrinfo: Name does not resolve)
Exiting; failed to retrieve certificate and waitforcert is disabled
testing the puppet/puppet-agent-alpine image .

Any ideas?

**Comment by garethr** [comment]
Hi @qafro1. What exactly are you attempting to do with the image?

The agent images will, by default, try and connect to a Puppet master at `puppet:8140`. So if you don't have one (either via linking or a container with the correct network name, or a DNS record inserted at runtime for instance) then this would be expected.

If you're just trying to run a specific puppet command you can pass that to the container:

    docker run puppet/puppet-agent-alpine --help

Alternatively if you want a shell you can override the entry command:

    docker run -it --entrypoint sh puppet/puppet-agent-alpine  

If you'd like to provide a gist of the commands you're running I'm happy to help debug.

You may find the full examples in this repository useful, in particular maybe the compose demo: https://github.com/puppetlabs/puppet-in-docker-examples/tree/master/compose

**Comment by qafro1** [comment]
Hi

1st attempt it worked

Ran Puppet server - standalone and connected Puppet -agent -alpine image.

By following the instructions then I stopped the servers on aws.

But when I started up both servers again with the same cmd process it
didn't work!

I'll build a fresh ec2 aws instant and redo it.

Rgds
Godfrey

**Comment by stahnma** [comment]
Closing since this hasn't had an update since Nov 2016.
