### ISSUE TITLE
How do restart the  puppet/puppetserver-standalone with it's same docker data

### ISSUE THREAD

**Issue by qafro1** [puppetlabs/puppet-in-docker#21]
How do I restart the same  docker image and data and run --name puppet --hostname puppet -v ./code:/etc/puppetlabs/code/
 puppet/puppetserver-standalone 
to use the same docker data volume for the puppet agent ?

**Comment by stahnma** [comment]
You could mount the current agent dir into the server container `-v /etc/puppetlabs/code:/etc/puppetlabs/code` instead of `./code`
