### ISSUE TITLE
Puppetdb server gets created with wrong hostname

### ISSUE THREAD

**Issue by mterzo** [puppetlabs/puppet-in-docker#22]
I'm using 

```
mterzo@ubuntu:~$ cat /etc/issue.net 
Ubuntu 14.04.3 LTS
root@puppet:/#` mterzo@ubuntu:~$ docker -v
Docker version 1.12.5, build 7392c3b
mterzo@ubuntu:~$ docker-compose -v
docker-compose version 1.7.0, build 0d7bf73
```

When puppetdb comes up the docker container is creating the cert for puppetdb.localdomain, even when attempt to set the hostname.

I've modified the docker container to use `puppet config set certname to <hostname>`.

I'll put up a PR for this shortly.

**Comment by MWilsonPuppet** [comment]
Closing this as @mterzo PR has been merged.Thanks @mterzo
