### ISSUE TITLE
Puppet Enterprise in docker

### ISSUE THREAD

**Issue by cdenneen** [puppetlabs/puppet-in-docker#28]
In order to "test" some things like Console and other pieces of PE. It would be nice for a box that had a complete PE setup for testing. It still uses the default free 10 license which should be good enough for testing.

**Comment by garethr** [comment]
Hi @cdenneen. This is definitely something we're interested in, and have done some prototyping around. Unfortunately however it's not something we have planned for the immediate future. The best bet is to talk to your Puppet account manager and pass on that feedback. The more we hear this is useful to customers (here and through other channels) the more likely we'll be to prioritise the work.

I'll leave this issue open as it's a good place to point others who may be interested too. Thanks.
