### ISSUE TITLE
puppetserver-standalone:2.7.2 not found

### ISSUE THREAD

**Issue by kirkins** [puppetlabs/puppet-in-docker#35]
When I build [puppetserver](https://github.com/puppetlabs/puppet-in-docker/blob/master/puppetserver/Dockerfile) from source I get an error about 2.7.2 not being found.

```
docker build . -t puppet/puppetserver
Sending build context to Docker daemon  7.168kB
Step 1/8 : FROM puppet/puppetserver-standalone:2.7.2
manifest for puppet/puppetserver-standalone:2.7.2 not found
```

I was able to build the image still by removing the `:2.7.2`, but I just wanted to point out that the specified version doesn't seem to be available.

**Comment by mmckinst** [comment]
The [Dockerfile currently in git has 2.7.2](https://github.com/puppetlabs/puppet-in-docker/blob/6ddeb0461127db8778b3944a4dec743bbb93e4cb/puppetserver-standalone/Dockerfile#L4) in it but the version in docker [still has 2.6.0 ](https://microbadger.com/images/puppet/puppetserver-standalone). It looks like the updated image was never pushed to docker hub.

**Comment by kirkins** [comment]
Link still says latest is 2.6.0, but when I build the image with 2.7.2 it works fine. Not sure what changed.
