### ISSUE TITLE
Add healthcheck to the server images

### ISSUE THREAD

**Issue by ColinHebert** [puppetlabs/puppet-in-docker#37]
Adding a healthcheck to the server image would allow docker to track whether or not puppet server is up and running healthily:

```Dockerfile
HEALTHCHECK \
  CMD [ $(curl -k -o /dev/null --silent --write-out '%{http_code}' https://localhost:8140/status/v1/simple) -eq 200 ]
```

**Comment by garethr** [comment]
I've just merged #38, this will be in the next set of images I should be pushing up today all being well
