### ISSUE TITLE
Autosign

### ISSUE THREAD

**Issue by luckyraul** [puppetlabs/puppet-in-docker#4]
`RUN puppet config set autosign true --section master`
May be it should be optional, or at least configurable

**Comment by garethr** [comment]
Agreed, or at least better documented.

I'm undecided about making this runtime configurable, or whether the inheritance model is a better approach - given folks may want to upload a custom autosign script. Thanks for raising here thought. If you (or anyone else reading this) have implementation ideas let me know.

**Comment by luckyraul** [comment]
In my opinion it should be in autosign.conf, which can be overwritten by docker file/folder mount. 
By default it's okay to be autosign true, but in separate file.

**Comment by vladgh** [comment]
What about something like:
```bash
# Configure puppet to use a certificate autosign script (if it exists)
AUTOSIGN="${AUTOSIGN:-}"
if [[ -n "$AUTOSIGN" ]]; then
  puppet config set autosign "$AUTOSIGN" --section master
fi
```
This will ignore this setting by default, but if needed, setting the environment variable will change the configuration:

EX:
`docker run ...` - will leave the default value in puppet unchanged
`docker run -e AUTOSIGN=true ...` - will allow naive autosigning (for testing)
`docker run -e AUTOSIGN='/path/to/signing/script' ...` - will use that script for signing.

**Comment by stahnma** [comment]
@vladgh that looks reasonable. If you put up a PR, I'd be happy to test it out.

**Comment by underscorgan** [comment]
We're migrating from GitHub issues to tickets on the Puppet JIRA. I've opened this issue there as https://tickets.puppetlabs.com/browse/CPR-578
