### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by ColinHebert** [puppetlabs/puppet-in-docker#43]
Hi @garethr, @gregohardy,

There are a few issues and PRs opened in this project. Is it still maintained? Is there a plan to make it production ready eventually?

**Comment by garethr** [comment]
@ColinHebert apologies for the inaction on here. I've been working on a few other things and other folks hadn't had the bandwidth to pick up some of the work. I'm going through all the PRs and issues now and resolving/replying. I'll also be releasing updated images with new versions of the various bits of software.

We're working on making that just part of the upstream process too to avoid this sort of lag. We've seen more than 500,000 downloads of the images to date and so we definitely want to continue shipping and improving these.
