### ISSUE TITLE
Puppet 5

### ISSUE THREAD

**Issue by luckyraul** [puppetlabs/puppet-in-docker#44]

**Comment by garethr** [comment]
@luckyraul good timing :) I've just spend today releasing a whole bunch of new images, including those for Puppet 5.

**Comment by luckyraul** [comment]
@garethr many thanks, please have a look for same issue https://github.com/puppetlabs/puppetlabs-image_build/issues/47

**Comment by luckyraul** [comment]
@garethr ```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Unable to determine lsbdistid, please install lsb-release first at /etc/puppetlabs/code/environments/production/modules/apt/manifests/params.pp:134:7 on node puppetdb
```

**Comment by garethr** [comment]
@luckyraul could I check which image this is affecting? The message seems to indicate it's the PuppetDB one `on node puppetdb`.

**Comment by luckyraul** [comment]
yes, puppetdb image

**Comment by garethr** [comment]
@luckyraul I've updated the puppetdb 5.0.0 image with lsb-release. Hopefully that resolves your issue. If not if you culd open an new issue with a few details of how to recreate I'll try and take a look next week. Thanks for testing these out so quickly, always much appreciated.

**Comment by luckyraul** [comment]
@garethr  

puppetdb: java.lang.Exception: PostgreSQL 9.5 is no longer supported.  Please upgrade to 9.6.

**Comment by garethr** [comment]
Ah, sorry. I hadn't pushed the last postgres image. There should be a 9.6.3 tag and latest should point to that now. Thanks.
