### ISSUE TITLE
Custom Ruby Function using `Resolv::DNS` Class does not work in Kubernetes

### ISSUE THREAD

**Issue by cmachler** [puppetlabs/puppet-in-docker#48]
Hello,

We have a custom function we use from (https://github.com/dalen/puppet-dnsquery) that queries DNS, specifically the `dns_lookup` function.

When using this function in Docker Compose it comes back with a result from DNS for example looking up `google.com` returns an array of `[147.22.32.62]`. The issue is using the same function in Kubernetes it returns an empty array `[ ]`.

Troubleshooting we have verified DNS works correctly in K8s by execing into the Puppet pod and performing a nslookup:

```
root@puppet-1205628959-zpgbg:/# nslookup google.com
Server:		10.43.0.10
Address:	10.43.0.10#53

Non-authoritative answer:
Name:	google.com
Address: 172.217.11.238
```

We also verified Ruby is working by creating a test ruby script to test the `Resolv::DNS` class:

```
require 'resolv'
p Resolv.getaddress('google.com')
```
Which works fine by invoking the script using `ruby` from the CLI, but trying to invoke the same script using puppetserver to run the ruby script returns nothing:

```
root@puppet-1205628959-zpgbg:/# puppetserver ruby dns-test.rb 
Resolv::ResolvError: no address for google.com
    getaddress at /opt/puppetlabs/server/apps/puppetserver/jruby-1_7.jar!/META-INF/jruby.home/lib/ruby/1.9/resolv.rb:98
    getaddress at /opt/puppetlabs/server/apps/puppetserver/jruby-1_7.jar!/META-INF/jruby.home/lib/ruby/1.9/resolv.rb:48
        (root) at dns-test.rb:3
          each at org/jruby/RubyRange.java:476
        (root) at dns-test.rb:2
        invoke at jruby_core.clj:277
        invoke at jruby_core.clj:271
  invokeStatic at ruby.clj:9
        invoke at ruby.clj:6
  invokeStatic at subcommand.clj:44
        invoke at subcommand.clj:33
  invokeStatic at subcommand.clj:60
        invoke at subcommand.clj:56
  invokeStatic at ruby.clj:13
      doInvoke at ruby.clj:11
  invokeStatic at core.clj:646
  invokeStatic at main.clj:314
        invoke at main.clj:310
  invokeStatic at main.clj:421
      doInvoke at main.clj:384
```

Any help would be greatly appreciated.

-Chris

**Comment by cmachler** [comment]
Found that in Kubernetes the `dns_lookup` lookup function in Puppet needs to be fully qualified with the trailing period. Once the lookup was fully qualified, it resolved with no problem in Puppet. If the trailing period was not there it was appending the search domains from `resolv.conf` to the FQDN's.

**Comment by garethr** [comment]
@cmachler thanks for reporting, and then letting us know you found a solution. We'll have to put some Kubernetes examples together in the future.
