### ISSUE TITLE
Health check high CPU usage

### ISSUE THREAD

**Issue by vladgh** [puppetlabs/puppet-in-docker#57]
https://github.com/puppetlabs/puppet-in-docker/blob/304f9c0321248a26b7fcf95a5871066b7ff4bb06/puppetserver-standalone/Dockerfile#L46-L48

The healthcheck for the puppetserver-standalone image uses puppet to get the certificate paths. This adds an unnecessary burden to the CPU for every interval. In the graph below on a 4GB RAM / 1 Core virtual instance that means an average of 25% cpu and 0.7 system load when idle. 

I think a simple `hostname` interpolation would be much better (ex: `--cert "/etc/puppetlabs/puppet/ssl/certs/$(hostname).pem"`), which should work just as well, but keep the load to a minimum. I could open a PR if needed.

![image](https://user-images.githubusercontent.com/370069/34320308-e31ad7b0-e7bc-11e7-8451-76fd3e6b3eb1.png)

**Comment by stahnma** [comment]
Feel free to open a PR here. I think in this exact case, you're right hostname would be fine. In most cases though there is no promise that certname and hostname are the same. Even with this container set, if you provide your own SSL directory, we have no idea if that will be true.

**Comment by underscorgan** [comment]
We're migrating from github issues to using ticket in the Puppet JIRA (tickets.puppet.com). I've opened this issue there as https://tickets.puppetlabs.com/browse/CPR-574
