### ISSUE TITLE
Service agent fail!

### ISSUE THREAD

**Issue by lcamhoa** [puppetlabs/puppet-in-docker#58]
When I run the command  ``` puppet  resource service agent ensure=running -d``` in puppet-agent container . I got these error

```
Debug: Executing: '/usr/sbin/service agent status'
Debug: Service[agent](provider=debian): Could not find agent in /etc/init.d
Debug: Service[agent](provider=debian): Could not find agent.sh in /etc/init.d
Error: Could not find init script for 'agent'
Error: /Service[agent]/ensure: change from 'stopped' to 'running' failed: Could not find init script for 'agent'
```
And, it 's the same issue with puppetserver. Can anyone help?

**Comment by stahnma** [comment]
You shouldn't run that in a container. The container is the service. There isn't really an init system underneath them. If you want to start the puppet agent (that is containerized) just start the container.
