### ISSUE TITLE
Tag latest image with version tag on Docker Hub

### ISSUE THREAD

**Issue by agarstang** [puppetlabs/puppet-in-docker#62]
Additionally tag latest image with version (currently `5.3.2`). Righ now it's impossible to pin your child dockerfiles to a the latest version; you have to use "latest" which will roll forward.

**Comment by stahnma** [comment]
@shrug did you get this done?

**Comment by shrug** [comment]
Yep, we should have both a 'latest' and the version tagged for the builds that went up yesterday

**Comment by agarstang** [comment]
Not pull-able from Docker Hub at the moment.
```
adam@adam-ThinkPad-T520:~/Documents/Dev/puppet-in-docker$ docker pull puppet/puppetserver:5.3.2
Error response from daemon: manifest for puppet/puppetserver:5.3.2 not found
```

**Comment by stahnma** [comment]
@shrug can we tag the 5.3.2 one as well? (I don't think we need to tag all old ones, but from now one we should probably tag)

**Comment by shrug** [comment]
The latest Puppetserver release is 5.3.0 from earlier this week. It's tagged as 5.3.0 and 'latest'

**Comment by shrug** [comment]
The latest releases have been tagged and pushed
