### ISSUE TITLE
Usability of puppet-agent-ubuntu image

### ISSUE THREAD

**Issue by vladgh** [puppetlabs/puppet-in-docker#8]
Hello, I am trying to implement the agent image in my testing environment and I ran into a few issues.

In general it's considered best practice to do `apt-get clean && rm -rf /var/lib/apt/lists/*` after `apt-get install` in order to keep the image size small. However, when testing the `puppet/puppet-agent-ubuntu` image, I encountered the following type of error, which makes sense given that apt caches are cleared:

```bash
$ docker run --rm -it  puppet/puppet-agent-ubuntu resource package ruby ensure=present
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install ruby' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package ruby
Error: /Package[ruby]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install ruby' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package ruby
package { 'ruby':
  ensure => 'purged',
}
```

What would be the best approach to this problem? Should I implement an `apt update` in the manifests?

What about errors like `Unable to determine lsbdistid, please install lsb-release first at /etc/puppetlabs/code/environments/production/modules/apt/manifests/params.pp:154:7`? Should this be added to the image?

**Comment by garethr** [comment]
Hi @vladgh. Thanks for the feedback.

1. As you note this is a clash between keeping the image small, and your testing usecase. The main idea with the agent images is either for [mounting Puppet into other images](https://github.com/puppetlabs/puppet-in-docker-examples/tree/master/puppet-at-runtime) or [using Puppet from within the container on the host](https://github.com/puppetlabs/puppet-in-docker-examples/blob/master/atomic/Vagrantfile#L62). Presuming you're using this for testing purposes I'd probably either use a manifest which runs apt-get before installing packages, or use the image as a base with `FROM` and add an additional RUN line.

2. Adding lsb-release might be a good idea. I'll look into that too once I test with the above usecases.

**Comment by vladgh** [comment]
Thank you @garethr, the two described scenarios are quite interesting. I will look into it.
